### ISSUE TITLE
Photos in the instructions

### ISSUE THREAD

**Issue by goodatcooking** [simmerwp/simmer#118]
Can I add step-by-step photos to the instruction? How to do it?
Thanks!

**Comment by laralfield** [comment]
Hi there! We only provide code support (on a theme-by-theme basis because all WordPress themes work differently with our recipe plugin) to active members. You can find more information about our membership benefits here https://simmerwp.com/membership/. Our Issues here on Github track only bugs in the core plugin code and questions relating to code that are contributed on an open source basis. Feel free to email us anytime at hi@simmerwp.com. Thanks! Lara
