### ISSUE TITLE
Recipe Pages Showing Stray Code

### ISSUE THREAD

**Issue by pacdude** [simmerwp/simmer#120]
http://www.abakerskitchen.com/recipes/recipe/corys-boneless-chicken-adobo/

There's a spare bit of code at the top of the page and I can't figure out exactly what to edit to fix it.

**Comment by laralfield** [comment]
Hi there! We only provide code support (on a theme-by-theme basis because all WordPress themes work differently with our recipe plugin) to active members. You can find more information at http://simmerwp.com. Our Issues here on Github track only bugs in the core plugin code and questions relating to code that are contributed on an open source basis. Feel free to email us anytime at hi@simmerwp.com. Thanks! Lara

**Comment by laralfield** [comment]
Hi there! We only provide code support (on a theme-by-theme basis because all WordPress themes work differently with our recipe plugin) to active members. You can find more information about our membership benefits here https://simmerwp.com/membership/. Our Issues here on Github track only bugs in the core plugin code and questions relating to code that are contributed on an open source basis. Feel free to email us anytime at hi@simmerwp.com. Thanks! Lara
