### ISSUE TITLE
Bugs in editor

### ISSUE THREAD

**Issue by shaybocks** [simmerwp/simmer#134]
I'm noticing a couple of bugs when creating new recipes:

Main WSIWYG editor - I accidentally pasted in the ingredients into the first field (visual) and deleted, but after I published the recipe the ingredients came back.  This happened several more times before I thought to delete from the text editor.

Also, I could not delete line items in ingredients or instructions until I published.  Once I published, I deleted and saved.  This is probably annoying for others though.  

And one last thing for now--the bulk copy/paste editor has no way of recognizing headings.  Is there a way to handle this?

**Comment by laralfield** [comment]
If a recipe is displaying information in the individual fields from a previous save, try deleting the recipe and creating a new recipe. We'll work on the problem of fields displaying past entries on a continual basis but it might not be isolated to Simmer alone.

Right now we're not adding any newly recognized formatting to the bulk copy/paste editor because it provides a lot of functionality out-of-the-box. Since recipe descriptions are not typically meant to be blog post replacements for Simmer when newly activated, there should not be a need to add headings in every instance, especially when a short description will work well for most recipes. 

Thanks!!

**Comment by shaybocks** [comment]
Thanks for considering this Lara. 

Headings are important for recipes that have multiple parts.  Example - Cake and Icing.  Headings help to separate which ingredients and instructions apply to the cake vs the icing.

**Comment by laralfield** [comment]
@shaybocks, subheadings are already a feature of both ingredient and instruction lists. They will not always be automatically recognized by our automatic bulk copy/paste tool, however. So you'll need to create sub-headings manually in Simmer's existing interface. 

Let me know if you have any questions about the sub-headings feature here. Thank you!
