### ISSUE TITLE
Plurals for non-abbreviated measurement amounts, abbreviation setting error

### ISSUE THREAD

**Issue by laralfield** [simmerwp/simmer#66]
This is a two-parter :) 

1. Right now plurals for non-abbreviated measurement amounts are not appearing. So for example, 1 1/2 cups is being displayed as 1 1/2 cup. Exampe here: http://laralittlefield.pub/recipes/recipe/strawberry-summer-cake/

2. On that same note, the settings for recipes for http://laralittlefield.pub are set to the abbreviated format, but as you can see the non-abbreviated format is being used instead. Here's the settings field in question for this install: 
![screen shot 2015-07-02 at 9 58 54 am](https://cloud.githubusercontent.com/assets/1518034/8478688/f6ce5c68-20a0-11e5-846b-ce50f77c8bd3.png)

I suspect the two issues might be linked so have included them together here :)

**Comment by rumspeed** [comment]
Confirmed. We are seeing both of these issues as well. The option is set to show abbreviations and the full name is displayed in singular form. Here is a link to the first recipe we published:
http://lifeuntethered.net/food-drink/recipe/basic-pizza-dough-for-the-campfire/

I took a look under the hood and here is what I can see...

**The calling function is not passing in the $count.**
https://github.com/simmerwp/simmer/blob/master/core/recipes/items/ingredients/class-simmer-recipe-ingredient.php#L141
		$unit = $this->get_unit_label( $unit );

**The receiving function is defaulting to 1 since nothing is passed.**
https://github.com/simmerwp/simmer/blob/master/core/recipes/items/ingredients/class-simmer-recipe-ingredient.php#L315
	public static function get_unit_label( $unit, $count = 1 ) {

With a little more time I could submit a pull request but you could likely fix it faster than I can. If you would like me to do so, please let me know and I'd be happy to help.

**Comment by rumspeed** [comment]
I found a fix for the bug. You can see that I have the code working in production now by reviewing the recipe again.
http://lifeuntethered.net/food-drink/recipe/basic-pizza-dough-for-the-campfire/

Here is what I did:

**add this line below L134 in the same file:**
		$count = simmer_get_recipe_item_meta( $this->id, 'amount', true );

**then modify line L142 (was L141) to include the new variable**
		$unit = $this->get_unit_label( $unit , $count );


This isn't an official pull request but here is a screenshot of the code changes. :)
![screenshot 2015-07-26 13 20 13](https://cloud.githubusercontent.com/assets/4145412/8895030/6c6b4f7a-3399-11e5-95e3-792df94eb8c3.png)

**Comment by laralfield** [comment]
Hey @rumspeed Scot, thanks so much for this!! We really appreciate it, and will get the code pushed ourselves based on what you've shared here asap. Do you have a site or blog URL we can link to to thank you in our next release notes? Thanks very much.

**Comment by rumspeed** [comment]
It was fun squashing that bug. My wife was working on her first recipe using Simmer and asked me about the plural form of the units. Shortly after she published the post, I had the fix for it.

Please use rumspeed.com for the URL. That would be awesome! I'm happy to help.

Cheers to open source software!

**Comment by laralfield** [comment]
@rumspeed So glad you had fun :+1: and that your wife is up and running with her recipe publishing. Thanks for the confirmation, and I'll let you know when those are up! Talk to you soon 🎉

**Comment by laralfield** [comment]
This Issue is now 100% solved with Simmer version 1.3.5 just released. Thanks so much again, @rumspeed. Please feel free to submit pull requests for anything else at anytime. We have the Spanish language files ready now which we'll be installing next week.
